komisariat

1.Pracownicy
stanowisko
imię
nazwisko
wiek
wykrztałcenie
nr_odznaki
----------------------------------
2.Sprzęt
nazwa
miejsce_położenia
id_przedmiotu
ilość
---------------------------------
3.zatrzymania
powód
data
godzina
kara
---------------------------------
4.funkcjonariusze
imię_funkcjonariusza
nazwisko_funkcjonariusza
nr_odznaki_funkcjonariusza
służba
---------------------------------
5.radiowozy
sprawność
miejsca(dla osób)
nr_rejestracji
nr_radiowozu
typ_auta
oznakowanie
wyposażenie
---------------------------------
6.badania_funkcjonariuszy
choroby
lekarstwa
badania
aktualność_badań
przeciwwskazania
--------------------------------
7.zwwierzęta_służące_w_komisariacie
imię_psa
rasa_psa
szkolenia
-------------------------------
8.kontrola_sprawności_sprzętu
data_kontroli
id_kotroli
następna_kontrola